import Link from "next/link";
import { getSportsTracking } from "@/db/queries-sports-tracking";
import { trackingFilters,trackingTotals,TRACKING_SPORTS,TRACKING_SIGNALS,TRACKING_RESULTS } from "@/lib/sports-tracking";
import s from "./tracking.module.css";
export const dynamic="force-dynamic";
const title=(v:string)=>v.replace(/^mlb_/,"").replaceAll("_"," ");
const signed=(v:number)=>`${v>0?"+":""}${v.toFixed(2)}`;
const rate=(w:number,l:number)=>w+l?`${(w/(w+l)*100).toFixed(1)}%`:"—";
export default async function TrackingPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
 const filters=trackingFilters(await searchParams);
 let data;try {data=await getSportsTracking(filters);} catch {return <section className={s.page}><Link href="/sports">Sports</Link><h1>Tracking</h1><p role="alert">Tracking records are unavailable right now. This does not mean there are no signals. Please reload to retry.</p></section>;}
 const totals=trackingTotals(data.groups),pages=Math.max(1,Math.ceil(totals.total/100));
 const href=(page:number)=>`/sports/tracking?${new URLSearchParams({...filters,page:String(page)})}`;
 return <section className={s.page}>
  <header><Link href="/sports">Sports</Link><h1>Tracking</h1><p>Line-movement results · MLB, NFL, CFB and tennis</p></header>
  <form className={s.filters} action="/sports/tracking"><label>Sport<select name="sport" defaultValue={filters.sport}><option value="all">All sports</option>{TRACKING_SPORTS.map(v=><option key={v} value={v}>{v.toUpperCase()}</option>)}</select></label><label>From<input type="date" name="from" defaultValue={filters.from}/></label><label>To<input type="date" name="to" defaultValue={filters.to}/></label><label>Signal<select name="signal" defaultValue={filters.signal}><option value="all">All signals</option>{TRACKING_SIGNALS.map(v=><option key={v} value={v}>{title(v)}</option>)}</select></label><label>Result<select name="result" defaultValue={filters.result}><option value="all">All results</option>{TRACKING_RESULTS.map(v=><option key={v} value={v}>{title(v)}</option>)}</select></label><button>Apply filters</button><Link href="/sports/tracking">Reset</Link></form>
  <div className={s.cards}><article><span>Signals</span><strong>{totals.total}</strong></article><article><span>Wins – Losses</span><strong>{totals.wins} – {totals.losses}</strong></article><article><span>Pushes / Draws</span><strong>{totals.pushes} / {totals.draws}</strong></article><article><span>Void / Pending</span><strong>{totals.voids} / {totals.pending}</strong></article><article><span>Win rate</span><strong>{rate(totals.wins,totals.losses)}</strong></article><article><span>Net units · {totals.priced} priced</span><strong>{totals.priced?signed(totals.units):"—"}</strong></article></div>
  <p className={s.note}>One record per original prospective signal; repeat observations and retrospective backfills are excluded. Dates refer to the game date. Multiple signals can refer to the same game. Win rate = wins ÷ (wins + losses). Pushes are exact line matches; draws are explicitly recorded draws; voids include no-action results and historical voids without a reason. They stay separate from pending outcomes.</p>
  <h2>Records by sport and signal</h2><p className={s.note}>Markets and detector versions are kept separate. Units assume one unit at the frozen entry price; missing prices are excluded. ROI uses only priced, resolved records. These records describe observations, not a proven betting edge.</p>
  <div className={s.scroll}><table><thead><tr>{['Sport / signal','Market / version','Signals / games','W–L','Push / Draw','Void','Pending / other','Win rate','Units / priced','ROI'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.groups.map(g=><tr key={`${g.sport}:${g.signal}:${g.market}:${g.version}`}><td><b>{g.sport.toUpperCase()}</b><small>{title(g.signal)}</small></td><td>{g.market}<small>{g.version}</small></td><td>{g.total} / {g.events}</td><td>{g.wins}–{g.losses}</td><td>{g.pushes} / {g.draws}</td><td>{g.voids}</td><td>{g.pending} / {g.unavailable}</td><td>{rate(g.wins,g.losses)}</td><td>{g.units==null?'—':signed(g.units)} / {g.priced}</td><td>{g.priced&&g.units!=null?`${(g.units/g.priced*100).toFixed(1)}%`:'—'}</td></tr>)}</tbody></table></div>{!data.groups.length&&<p className={s.empty}>No recorded signals match these filters.</p>}
  <h2>Signal ledger</h2><div className={s.scroll}><table><thead><tr>{['Game date','Sport / game','Signal / market','Entry','Result','Reason','Units','Observed ET'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.entries.map(e=><tr key={e.id}><td>{e.date}</td><td>{e.sport.toUpperCase()}<small>{e.matchup}</small></td><td>{title(e.signal)}<small>{e.market} · {e.version} · #{e.id}</small></td><td>{e.side}{e.entryLine==null?'':` ${e.entryLine}`}<small>{e.entryPrice==null?'Price unavailable':`${e.entryPrice>0?'+':''}${e.entryPrice}`}</small></td><td data-result={e.result}>{e.result}</td><td>{e.reason??(e.result==='pending'?'Awaiting result':'Not recorded')}</td><td>{e.units==null?'—':signed(e.units)}</td><td>{new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(e.observedAt))}</td></tr>)}</tbody></table></div>
  <nav className={s.pagination} aria-label="Ledger pages">{filters.page>1&&<Link href={href(filters.page-1)}>← Previous</Link>}<span>Page {filters.page} of {pages} · 100 records per page</span>{filters.page>pages&&<Link href={href(1)}>Return to first page</Link>}{filters.page<pages&&<Link href={href(filters.page+1)}>Next →</Link>}</nav>
 </section>;
}
