/**
 * Phase 0 regression fixture (spec P0-AC2).
 *
 * Pins the CURRENT Showdown optimizer behavior against a fixed, deterministic
 * player pool and the current default Showdown settings. Later phases must not
 * change this output silently: if a phase alters generation, this test fails
 * and the change must be acknowledged and the fixture re-baselined on purpose.
 *
 * It also asserts Phase 0's build-identity contract: nflBuildInfo() reports a
 * commit SHA, settings-schema version, optimizer version and scorer version,
 * and never fabricates a build time it cannot support.
 */
import assert from "node:assert/strict";
import { optimizeNflLineups, type NflOptimizerPlayer, type NflOptimizerSettings } from "../src/app/dfs/nfl/nfl-optimizer";
import { nflBuildInfo, shortCommitSha } from "../src/lib/nfl-dfs/build-info";

/** A fixed two-team Showdown pool. Salaries and projections are arbitrary
 *  mechanics fixtures, not fitted NFL numbers — only determinism matters. */
function fixedShowdownPool(): NflOptimizerPlayer[] {
  const rows: Array<[number, string, NflOptimizerPlayer["position"], string, number, number]> = [
    [2001, "AAA QB", "QB", "AAA", 10800, 20],
    [2002, "AAA RB", "RB", "AAA", 9000, 15],
    [2003, "AAA WR1", "WR", "AAA", 9600, 17],
    [2004, "AAA WR2", "WR", "AAA", 6400, 11],
    [2005, "AAA TE", "TE", "AAA", 4000, 8],
    [2006, "AAA K", "K", "AAA", 3600, 7],
    [2007, "AAA DST", "DST", "AAA", 3200, 6],
    [2008, "BBB QB", "QB", "BBB", 10400, 19],
    [2009, "BBB RB", "RB", "BBB", 8600, 14],
    [2010, "BBB WR1", "WR", "BBB", 9200, 16],
    [2011, "BBB WR2", "WR", "BBB", 6000, 10],
    [2012, "BBB TE", "TE", "BBB", 3800, 7],
    [2013, "BBB K", "K", "BBB", 3400, 6],
    [2014, "BBB DST", "DST", "BBB", 3000, 5],
  ];
  return rows.map(([dkPlayerId, name, position, team, salary, proj]) => ({
    id: dkPlayerId,
    dkPlayerId,
    captainDkPlayerId: dkPlayerId + 100_000,
    name,
    position,
    team,
    opponent: team === "AAA" ? "BBB" : "AAA",
    gameKey: "AAA@BBB",
    salary,
    captainSalary: Math.round(salary * 1.5),
    isOut: false,
    projectionStatus: "historical",
    historyGames: 6,
    ourProj: proj,
    floorFpts: proj * 0.7,
    ceilingFpts: proj * 1.4,
    boomRate: 0.2,
    avgFptsDk: proj,
    fantasyprosProj: null,
    linestarProj: null,
    linestarOwnPct: null,
    customProj: null,
  }));
}

function baselineSettings(): NflOptimizerSettings {
  // The current shipped Showdown defaults.
  return {
    format: "showdown",
    mode: "gpp",
    projectionSource: "our",
    allowDkFallback: true,
    nLineups: 5,
    minSalary: 49000,
    maxExposure: 0.6,
    minUnique: 2,
    stackPassCatchers: 1,
    bringBack: true,
    randomness: 0,
    lockedPlayerIds: [],
    excludedPlayerIds: [],
    minExposureByPlayer: {},
    maxExposureByPlayer: {},
  };
}

function fingerprint(lineups: ReturnType<typeof optimizeNflLineups>["lineups"]): string {
  // A stable, human-readable signature of the portfolio: each lineup's player
  // ids in slot order plus its total salary.
  return lineups
    .map((l) => `${l.lineupNumber}:${l.slots.map((s) => `${s.slot}=${s.player.dkPlayerId}`).join(",")}|$${l.totalSalary}`)
    .join(" || ");
}

/**
 * The FROZEN default-behavior fingerprint, generated by running this exact
 * fixture through origin/main's optimizer (verified byte-identical 2026-09-21).
 * A phase that changes default no-policy output must fail here and re-baseline
 * DELIBERATELY, with the change acknowledged in the commit — never silently.
 */
const EXPECTED_FINGERPRINT =
  "1:CPT=2008,FLEX1=2005,FLEX2=2006,FLEX3=2001,FLEX4=2003,FLEX5=2004|$50000" +
  " || 2:CPT=2005,FLEX1=2010,FLEX2=2008,FLEX3=2012,FLEX4=2003,FLEX5=2001|$49800" +
  " || 3:CPT=2001,FLEX1=2005,FLEX2=2008,FLEX3=2007,FLEX4=2003,FLEX5=2011|$49400";

function main() {
  // --- Build identity (Phase 0 P0-AC1) ---
  const build = nflBuildInfo();
  assert.ok(build.commitSha.length > 0, "commit SHA must be present");
  assert.equal(build.settingsSchemaVersion, "nfl_gpp_portfolio_v1");
  assert.equal(build.optimizerVersion, "nfl-dfs-ilp-v6-punt-policy");
  assert.equal(build.scorerVersion, "nfl-dk-scenario-v1");
  assert.ok(["unknown"].includes(build.buildTime) || Number.isFinite(Date.parse(build.buildTime)),
    "build time is either a real ISO timestamp or the honest 'unknown' sentinel");
  assert.ok(shortCommitSha("abcdef1234567").length <= 7);
  assert.equal(shortCommitSha("local-uncommitted"), "local-uncommitted");

  // --- Deterministic portfolio (Phase 0 P0-AC2) ---
  const pool = fixedShowdownPool();
  const settings = baselineSettings();
  const first = optimizeNflLineups(pool, settings);
  const replay = optimizeNflLineups(fixedShowdownPool(), baselineSettings());

  // The point is determinism + legality, not a specific count: with a small
  // pool, minUnique 2 and a $49k floor the solver may stop early. That early
  // stop is itself the spec's §2 finding (a high floor compresses construction)
  // and is pinned here so a later phase changing it is a deliberate act.
  assert.ok(first.lineups.length >= 1 && first.lineups.length <= 5, "produces between one and five lineups");
  assert.equal(first.lineups.length, replay.lineups.length, "same count on replay");
  assert.equal(fingerprint(first.lineups), fingerprint(replay.lineups), "generation is deterministic with randomness 0");
  // The real regression pin: byte-identical to origin/main's output for this
  // fixture. Determinism alone cannot detect a silent default-behavior change.
  assert.equal(fingerprint(first.lineups), EXPECTED_FINGERPRINT, "default no-policy output matches the frozen main-parity fingerprint");

  // Regression (found in review): the flat max-exposure default must always
  // permit at least one appearance. floor(0.6 × 1) = 0 once emptied the pool,
  // so a single-lineup request produced ZERO lineups where main produced one.
  const single = optimizeNflLineups(fixedShowdownPool(), { ...baselineSettings(), nLineups: 1, minSalary: 45000 });
  assert.equal(single.lineups.length, 1, "one requested lineup at 60% max exposure generates one lineup");

  // Every lineup is a legal Showdown roster: 1 CPT + 5 FLEX, unique players, under cap, over floor.
  for (const lineup of first.lineups) {
    assert.equal(lineup.slots.length, 6, "showdown roster is six slots");
    assert.equal(lineup.slots.filter((s) => s.slot === "CPT").length, 1, "exactly one captain");
    assert.equal(new Set(lineup.playerIds).size, 6, "no duplicate players in a lineup");
    assert.ok(lineup.totalSalary <= 50000, "under the salary cap");
    assert.ok(lineup.totalSalary >= settings.minSalary, "at or above the lineup salary floor");
  }

  // Uniqueness across the portfolio: each pair differs by at least minUnique.
  for (let i = 0; i < first.lineups.length; i++) {
    for (let j = i + 1; j < first.lineups.length; j++) {
      const shared = first.lineups[i].playerIds.filter((id) => first.lineups[j].playerIds.includes(id)).length;
      assert.ok(6 - shared >= settings.minUnique, `lineups ${i} and ${j} respect min-unique`);
    }
  }

  // The $49k floor on a small pool compressing the portfolio below the request
  // is exactly the structural limitation the spec sets out to fix. Record it.
  if (first.lineups.length < settings.nLineups) {
    console.log(`Baseline note: requested ${settings.nLineups}, produced ${first.lineups.length} — the $${settings.minSalary} floor compresses construction (spec §2).`);
  }

  console.log("NFL GPP Phase 0 baseline: build identity + deterministic legal Showdown portfolio passed.");
  console.log("Baseline fingerprint:\n  " + fingerprint(first.lineups));
}

main();
