import assert from 'node:assert/strict';
import {calibratedRelease,readCalibratedProjection,readPositionWorkloadProjection,type CalibrationSnapshot} from '../src/lib/nfl-dfs/calibrated-projection';
import {selectedWorkload,validateWorkloadPositions,WORKLOAD_POSITIONS,type WorkloadPositions} from '../src/lib/nfl-dfs/workload-selection';
import {optimizeNflLineups,type NflOptimizerPlayer,type NflOptimizerSettings} from '../src/app/dfs/nfl/nfl-optimizer';
const now=Date.parse('2026-09-12T12:00:00Z'),kickoff='2026-09-13T17:00:00Z';
const target={ffPlayerId:1,position:'QB',team:'BUF',opponent:'MIA',gameInfo:'BUF@MIA 09/13/2026 01:00PM ET'};
const snapshots=Object.fromEntries((['QB','RB','TE'] as const).map(position=>[position,{id:position,playerId:1,season:2026,week:1,capturedAt:new Date(now-1000).toISOString(),kickoff,payload:{position,team:'BUF',opponent:'MIA',source_study_digest:calibratedRelease.studyDigest,history_cutoff:[2025,18],prior_opportunity:8,baseline:10,p10:5,p90:15,candidate:{prediction:40,p10:30,median:38,p90:60,boom_probability:.3,recipe_digest:calibratedRelease.positions[position].recipeDigest}}}])) as Record<'QB'|'RB'|'TE',CalibrationSnapshot>;
for(const position of ['QB','RB','TE'] as const){const snapshot=snapshots[position],t={...target,position};assert.equal(readPositionWorkloadProjection(snapshot,t,2026,1,now).projection!.releaseVersion,'nfl-dfs-position-workload-opt-in-v1');assert.equal(readPositionWorkloadProjection(snapshot,t,2026,1,now).projection!.mean,40);assert.equal(readPositionWorkloadProjection(snapshot,t,2026,1,now).projection!.priorOpportunity,8);if(position!=='QB')assert.equal(readCalibratedProjection(snapshot,t,2026,1,now).projection,null,'old calibrated gate must remain closed for RB/TE');
  for(const changed of [{...snapshot,week:2},{...snapshot,playerId:2},{...snapshot,capturedAt:new Date(now-73*3600000).toISOString()},{...snapshot,capturedAt:new Date(now+1000).toISOString()},{...snapshot,payload:{...(snapshot.payload as object),candidate:{prediction:40}}},{...snapshot,payload:{...(snapshot.payload as object),history_cutoff:[2026,1]}},{...snapshot,payload:{...(snapshot.payload as object),source_study_digest:'wrong'}}])assert.equal(readPositionWorkloadProjection(changed,t,2026,1,now).projection,null);
  assert.equal(readPositionWorkloadProjection(snapshot,{...t,opponent:'KC'},2026,1,now).projection,null);assert.equal(readPositionWorkloadProjection(snapshot,t,2026,1,Date.parse(kickoff)).projection,null);
}
let id=0;const pool:NflOptimizerPlayer[]=[];
for(const [team,opponent] of [['BUF','MIA'],['MIA','BUF'],['KC','DEN'],['DEN','KC']])for(const position of ['QB','RB','RB','WR','WR','WR','TE','DST'] as const){id++;pool.push({id,dkPlayerId:id,captainDkPlayerId:id+1000,name:`${team} ${position} ${id}`,position,team,opponent,gameKey:[team,opponent].sort().join('@'),salary:5000,captainSalary:7500,isOut:false,projectionStatus:'historical',ourProj:10,floorFpts:5,ceilingFpts:15,boomRate:.1,avgFptsDk:9,fantasyprosProj:null,linestarProj:null,linestarOwnPct:null,customProj:null});}
const upgrades=WORKLOAD_POSITIONS.map(position=>{const p=pool.find(p=>p.position===position)!;p.ourProj=1;p.floorFpts=.5;p.ceilingFpts=1.5;if(position==='WR')p.workload={mean:40,p10:30,p50:38,p90:60,targets:8,baselineTargets:5,historyGames:8,snapshotId:'wr',recipeDigest:'wr',rosterDigest:'roster',capturedAt:new Date(now-1000).toISOString(),kickoff,identity:'wr',season:2026,week:1,injuryAdjusted:false};else p.positionWorkload=readPositionWorkloadProjection(snapshots[position],{...target,position},2026,1,now).projection;return p;});
const all:WorkloadPositions={QB:true,RB:true,WR:true,TE:true},none:WorkloadPositions={QB:false,RB:false,WR:false,TE:false};
const settings:NflOptimizerSettings={format:'classic',mode:'gpp',projectionSource:'workload',workloadPositions:all,allowDkFallback:false,nLineups:1,minSalary:0,maxExposure:1,minUnique:1,stackPassCatchers:0,bringBack:false,randomness:0,lockedPlayerIds:[],excludedPlayerIds:[],minExposureByPlayer:{},maxExposureByPlayer:{}};
const before=JSON.stringify(pool);
for(const mode of ['cash','gpp'] as const){const base=optimizeNflLineups(pool,{...settings,mode,projectionSource:'our'}).lineups[0];assert.ok(upgrades.every(p=>!base.playerIds.includes(p.dkPlayerId)));const result=optimizeNflLineups(pool,{...settings,mode});const l=result.lineups[0];assert.ok(upgrades.every(p=>l.playerIds.includes(p.dkPlayerId)));assert.equal(l.projectedFpts,210);assert.equal(l.floorFpts,145);assert.equal(l.ceilingFpts,315);assert.equal(l.slots.filter(s=>s.projectionSource==='workload').length,4);assert.equal(l.totalSalary,45000);assert.deepEqual(result,optimizeNflLineups(pool,{...settings,mode}));
  for(const position of WORKLOAD_POSITIONS){const one={...none,[position]:true};const single=optimizeNflLineups(pool,{...settings,mode,workloadPositions:one}).lineups[0];assert.deepEqual(single.slots.filter(s=>s.projectionSource==='workload').map(s=>s.player.position),[position]);const sd=optimizeNflLineups(pool.filter(p=>['BUF','MIA'].includes(p.team)),{...settings,mode,format:'showdown',workloadPositions:one}).lineups[0];const cpt=sd.slots.find(s=>s.slot==='CPT')!;assert.equal(cpt.player.position,position);assert.equal(cpt.projectionSource,'workload');assert.equal(cpt.projection,60);}
}
assert.deepEqual(optimizeNflLineups(pool,{...settings,workloadPositions:undefined}).lineups[0].slots.filter(s=>s.projectionSource==='workload').map(s=>s.player.position),['WR'],'old saved settings stay WR-only');
assert.equal(selectedWorkload(upgrades[0],none),null);
assert.throws(()=>optimizeNflLineups(pool,{...settings,workloadPositions:none}),/Enable at least/);
assert.throws(()=>validateWorkloadPositions({...all,RB:'yes'} as unknown as WorkloadPositions),/true\/false/);
assert.throws(()=>optimizeNflLineups(pool.map(p=>({...p,positionWorkload:null,workload:null})),settings),/No eligible/);
assert.equal(JSON.stringify(pool),before);
console.log('Position workload: pinned QB/RB/TE gates, legacy isolation, all-position and independent cash/GPP selection, CPT scaling, controls and reproducibility passed.');
