"use client";
import Link from 'next/link';
import { useState } from 'react';
import report from '@/data/nfl-team-context.json';
import diagnostic from '@/data/nfl-role-context.json';
import RoleAllocation from './role-allocation';

type Coach={historical_caller_changes?:{season:number;effective_week:number;previous:string;next:string;source:string}[];caller_evidence?:{source:string;checked_at:string;status:string};play_caller?:string|null;previous_head_coach_history?:{week:number;date:string;name:string}[];head_coach:string;coordinator:string;checked_at:string;note:string;sources:string[]};
const pct=(v:number)=>`${(v*100).toFixed(1)}%`;
export default function TeamContext({viewedAt}:{viewedAt:number}){
  const [team,setTeam]=useState('SF');
  const [state,setState]=useState<'all'|'neutral'|'leading'|'trailing'>('neutral');
  const [player,setPlayer]=useState('');
  const [share,setShare]=useState('');
  const [playCount,setPlayCount]=useState('65');
  const selected=report.teams.find(t=>t.team===team)!;
  const profile=selected.profiles[state];
  const coach=selected.coaching as Coach|null;
  const chosen=selected.players.find(p=>p.id===player);
  const stale=viewedAt-Date.parse(report.as_of)>72*3600000||viewedAt<Date.parse(report.as_of);
  const callerStatus=!coach?.caller_evidence||viewedAt<Date.parse(coach.caller_evidence.checked_at)||viewedAt-Date.parse(coach.caller_evidence.checked_at)>30*86400000?'unresolved':selected.caller_status;
  const coachStale=!coach||viewedAt-Date.parse(coach.checked_at)>30*86400000||viewedAt<Date.parse(coach.checked_at);
  const eligible=chosen&&chosen.evidence_current&&!chosen.out&&!stale;
  const valid=profile&&eligible&&share.trim()!==''&&playCount.trim()!==''&&Number.isFinite(Number(share))&&Number(share)>=0&&Number(share)<=100&&Number.isFinite(Number(playCount))&&Number(playCount)>=0&&Number(playCount)<=150;
  const runs=Number(playCount)*(profile?.designed_run_rate??0);
  const dropbacks=Number(playCount)-runs;
  const attempts=dropbacks*(1-(profile?.scramble_rate??0)-(profile?.sack_rate??0));
  const targets=attempts*(profile?.target_rate??0);
  const panel='rounded-2xl border border-slate-200 bg-white p-5';
  return <main className="mx-auto max-w-7xl space-y-5 bg-slate-50 p-6 text-slate-900">
    <nav className="flex gap-5 text-teal-800"><Link href="/dfs/nfl">NFL DFS</Link><Link href="/dfs/nfl/model">Model Lab</Link><Link href="/dfs/nfl/model/workload">Salary upside research</Link></nav>
    <header className="rounded-2xl bg-teal-950 p-6 text-white"><h1 className="text-3xl font-bold">Current roster → team opportunity</h1><p className="mt-3">Use the team’s play environment to explore a newcomer’s workload. Historical scheme references and manual roles are not activated optimizer projections.</p></header>
    <section className={panel}><label className="font-semibold">Team <select className="rounded border p-2" value={team} onChange={e=>{setTeam(e.target.value);setPlayer('');setShare('');}}>{report.teams.map(t=><option key={t.team}>{t.team}</option>)}</select></label><p className="my-3 text-sm">Roster snapshot: {new Date(report.as_of).toUTCString()} · {stale?'Expired for current role use':'Within 72-hour research window at page load'}. Retrieval is not official game-day confirmation.</p><h2 className="font-bold">Coaching continuity: {coachStale?'unresolved / missing or expired evidence':selected.continuity.replaceAll('_',' ')}</h2><p className="my-2">{coach?`${coach.head_coach} / ${coach.coordinator}. ${coach.note}`:'Current head coach, coordinator and play-caller continuity have not all been verified.'}</p><p className="my-2 text-sm">Current play caller: {coach?.play_caller??'Unresolved'} ({callerStatus.replaceAll('_',' ')}). {coach?.caller_evidence&&<a className="underline text-teal-800" href={coach.caller_evidence.source}>Caller evidence</a>} Prior head coaches: {[...new Set(coach?.previous_head_coach_history?.map(r=>r.name)??[])].join(', ')||'Unresolved'}.</p><p className="text-sm text-amber-900">Last year’s rates are shown as historical reference. No automatic continuity adjustment or carryover forecast is enabled.</p>{coach?.sources.map((url,i)=><a key={url} className="mr-4 text-sm text-teal-800 underline" href={url}>Coaching source {i+1}</a>)}</section>
    {coach?.historical_caller_changes&&<section className={panel}><h2 className="font-bold">Recorded prior-season caller changes</h2>{coach.historical_caller_changes.map(c=><p key={`${c.season}-${c.effective_week}`} className="my-2">{c.season}, week {c.effective_week}: {c.previous} → {c.next}. <a className="underline text-teal-800" href={c.source}>Event source</a></p>)}<p className="text-sm">Selected verified events, not a complete season timeline. Historical team rates span these changes and must not be attributed to one caller.</p></section>}
    <section className={panel}><h2 className="text-xl font-bold">{report.historical_season} play distribution</h2><p className="my-2 text-sm">Neutral: within seven points through Q3. Leading/trailing: more than seven points, all quarters. Excludes kneels, spikes, no-play and two-point plays. Designed dropbacks include sacks and scrambles.</p><div className="grid gap-3 md:grid-cols-4">{Object.entries(selected.profiles).map(([label,p])=>p?<button key={label} onClick={()=>setState(label as typeof state)} className={`rounded-xl border p-3 text-left ${state===label?'border-teal-700 bg-teal-50':'border-slate-200'}`}><strong className="capitalize">{label}</strong><p className="text-sm">{p.plays.toLocaleString()} plays</p><div className="my-2 flex h-3 overflow-hidden rounded bg-indigo-500"><div className="bg-teal-500" style={{width:pct(p.designed_run_rate)}}/></div><p className="text-sm">Run {pct(p.designed_run_rate)} / dropback {pct(1-p.designed_run_rate)}</p></button>:<div key={label} className="rounded-xl border p-3">{label}: no eligible plays</div>)}</div><p className="mt-3 text-sm">Full-game historical average: {selected.profiles.all?.plays_per_game.toFixed(1)} eligible plays. Situation-specific rates are not full-game play counts.</p></section>
    <section className={panel}><h2 className="text-xl font-bold">Measured offensive tendencies</h2><p className="my-2 text-sm">Full-season observations, not current coaching forecasts. Bars use plays with recorded values; coverage shows how much evidence supports each rate.</p><div className="grid gap-4 sm:grid-cols-2">{Object.entries(selected.tendencies).map(([key,m])=><div key={key}><p className="capitalize font-semibold">{key.replaceAll('_',' ')}: {m.rate===null?'Unavailable':pct(m.rate)}</p><div className="my-2 h-3 overflow-hidden rounded bg-slate-100"><div className="h-full bg-teal-600" style={{width:m.rate===null?'0%':pct(m.rate)}} /></div><p className="text-xs">{m.known} recorded / {m.eligible} eligible plays</p></div>)}</div><p className="mt-3 text-sm">Red zone: opponent 1–20 yard line. Inside five: 1–5. Dropbacks include sacks and scrambles. Empty samples remain unavailable.</p></section>
    <details className={panel}><summary className="font-bold">Formation and personnel data coverage</summary><p className="my-3 text-sm">Matched by game and play ID, with duplicate joins rejected. Availability only: route labels do not measure every receiver’s routes run or prove a matchup advantage.</p>{Object.entries(selected.participation_audit).map(([key,m])=><div key={key} className="my-3"><p>{key.replaceAll('_',' ')}: {m.known} / {m.eligible} eligible plays</p><div className="h-2 rounded bg-slate-100"><div className="h-full rounded bg-indigo-500" style={{width:pct(m.eligible?m.known/m.eligible:0)}}/></div></div>)}</details>
    <section className={panel}><h2 className="text-xl font-bold">Where the historical opportunities went</h2><p className="my-2 text-sm">Positions come from the same historical game, not today’s roster. Unknown identities stay in the budget. These shares describe positions, not a newcomer’s guaranteed workload.</p><div className="grid gap-4 md:grid-cols-3">{Object.entries(selected.positional_opportunities).map(([key,m])=><div key={key}><h3 className="font-semibold capitalize">{key.replaceAll('_',' ')} · {m.opportunities}</h3>{Object.entries(m.positions).map(([position,count])=><div key={position} className="mt-2"><p className="text-xs">{position}: {count} ({m.opportunities?pct(count/m.opportunities):'Unavailable'})</p><div className="h-2 rounded bg-slate-100"><div className="h-full rounded bg-indigo-500" style={{width:pct(m.opportunities?count/m.opportunities:0)}}/></div></div>)}</div>)}</div><p className="mt-4 text-sm">Within-drive clock spacing: {selected.clock_spacing.mean_seconds?.toFixed(1)??'Unavailable'} seconds across {selected.clock_spacing.pairs} adjacent snap pairs. Same quarter and possession; includes play duration. This is a game-clock measure, not wall-clock pace.</p></section>
    <section className={panel}><h2 className="text-xl font-bold">Does role context improve DFS predictions?</h2><p className="my-2">Team-game workload and recent QB stability experiment: <strong>{diagnostic.passes_screen?'Passed retrospective screen':'Failed — not activated'}</strong>.</p><p className="text-sm">Same recorded WR games for both models. Existing model means production-algorithm replay with market inputs disabled, not archived live projections. Lower point error, interval score and 25-point Brier score are better. The interval score penalizes both overly wide ranges and outcomes outside the predicted floor/ceiling.</p><div className="overflow-auto"><table className="my-3 w-full text-left text-sm"><thead><tr>{['Season / games','Point error: existing → candidate','Floor/ceiling score','25-point probability error'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{Object.entries(diagnostic.seasons).map(([year,m])=><tr key={year} className="border-t"><td className="p-2">{year} / {m.n}</td><td>{m.production.mae.toFixed(2)} → {m.candidate.mae.toFixed(2)}</td><td>{m.production.interval80.toFixed(2)} → {m.candidate.interval80.toFixed(2)}</td><td>{m.production_brier25.toFixed(4)} → {m.candidate_brier25.toFixed(4)}</td></tr>)}</tbody></table></div><details className="my-3"><summary className="font-semibold">Separate workload estimates from uncertainty conditioning</summary><p className="my-2 text-sm">The same workload estimates with pooled errors have interval scores of {diagnostic.seasons['2024'].pooled_residual_ablation.interval80.toFixed(2)} (2024) and {diagnostic.seasons['2025'].pooled_residual_ablation.interval80.toFixed(2)} (2025). Conditioning on prior workload and QB history improves those ranges, but neither version beats the existing model overall. This comparison does not isolate QB history from workload conditioning.</p></details><p className="text-sm">Previously inspected seasons; not an untouched holdout. Current coaching records are never backdated into this replay. No historical salary-multiple or contest-winning claim.</p></section>
    <section className={panel}><h2 className="text-xl font-bold">Current roster and movement</h2><p className="my-2 text-sm">Prior teams come from recorded {report.historical_season} games. No record does not prove a player is a rookie. Rookie flags require provider rookie-year evidence. New-team target shares are never copied automatically.</p><div className="max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{['Player','Roster role / status','Movement','Opportunity basis'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{selected.players.map(p=><tr key={p.id} className="border-t"><td className="p-2">{p.name} · {p.position}</td><td>{stale?'Snapshot expired':p.role} / {p.status}{p.out?' · excluded':''}</td><td>{p.rookie?'Rookie':p.new_team?`New team from ${p.historical_teams.join('/')}`:p.historical_teams.length?'Returning team':'History unresolved'}</td><td>{p.opportunity_basis}</td></tr>)}</tbody></table></div></section>
    <section className={panel}><h2 className="text-xl font-bold">Explore a current player’s opportunity</h2><p className="my-2 text-sm">Explicit assumptions, not a role forecast. Uses the selected historical play mix for {state}. Change the total plays and a player’s share to see the opportunity budget. No fantasy points or probabilities are inferred from these assumptions.</p><div className="flex flex-wrap gap-4"><label>Player <select value={player} onChange={e=>{setPlayer(e.target.value);setShare('');}} className="block max-w-72 rounded border p-2"><option value="">Select player</option>{selected.players.filter(p=>['RB','WR','TE','FB'].includes(p.position)).map(p=><option key={p.id} value={p.id}>{p.name} · {p.position}</option>)}</select></label><label>Total plays<input className="block w-28 rounded border p-2" type="number" min="0" max="150" value={playCount} onChange={e=>setPlayCount(e.target.value)}/></label><label>Assumed share (%)<input className="block w-40 rounded border p-2" type="number" min="0" max="100" value={share} onChange={e=>setShare(e.target.value)}/></label></div><p className="my-2 text-sm">For RB/FB: share of designed team runs (including designed QB runs). For WR/TE: share of allocatable targets. QB scrambles and sacks do not become RB carries or receiver targets.</p>{!valid?<p className="text-amber-900">Choose a player with matching current, available roster evidence and enter valid assumptions. Out and stale records are not eligible.</p>:<div className="grid gap-3 sm:grid-cols-3">{[['Team designed runs',runs],['Team target budget',targets],[`${chosen!.name} ${['RB','FB'].includes(chosen!.position)?'carries':'targets'}`,(['RB','FB'].includes(chosen!.position)?runs:targets)*Number(share)/100]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-teal-50 p-4"><strong className="text-2xl">{Number(value).toFixed(1)}</strong><p className="text-sm">{label}</p></div>)}</div>}</section>
    <RoleAllocation key={team} members={selected.players} team={team} targets={profile?targets:NaN} carries={profile?runs:NaN} now={viewedAt} rosterDigest={report.roster_digest} scenario={state}/>
    <p className="text-sm">Role reference: {selected.prior_role_window.games} team games, weeks {selected.prior_role_window.weeks.join(', ')} of {report.historical_season}. Non-participation counts as zero opportunity within those team games. Saved scenarios include assumptions and roster evidence for reproducibility.</p>
    <details className={panel}><summary>Source and modeling limits</summary><ul className="list-disc pl-5">{report.limits.map(l=><li key={l}>{l}</li>)}</ul>{Object.entries(report.sources).map(([key,s])=><p key={key} className="my-2 break-all text-xs"><a className="underline" href={s.url}>{key}</a> · {s.sha256}</p>)}</details>
  </main>;
}
