"use client";
import Link from 'next/link';
import { useState } from 'react';
import report from '@/data/nfl-volume-share-report.json';

const number = (v: number) => v.toFixed(1);
export default function Report({viewedAt}:{viewedAt:number}) {
  const [team,setTeam]=useState(report.forward[0]?.team??'');
  const forecast=report.forward.find(f=>f.team===team);
  const age=(viewedAt-Date.parse(report.as_of))/3600000;
  const stale=age>72||age<0;
  const panel='rounded-2xl border border-slate-200 bg-white p-5';
  return <main className="mx-auto max-w-7xl space-y-6 bg-slate-50 p-5 text-slate-900 sm:p-8">
    <nav className="flex gap-5 text-sm text-teal-800"><Link href="/dfs/nfl">NFL DFS</Link><Link href="/dfs/nfl/model">Model Lab</Link><Link href="/dfs/nfl/history">Player Context</Link></nav>
    <header className="rounded-2xl bg-teal-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-teal-200">Projection research / volume and shares</p><h1 className="my-3 text-3xl font-bold">From team passes to receiver targets</h1><p>Forecast a team target budget, allocate prior receiver shares, and test the resulting DK points and player ranges.</p><p className="mt-3 text-sm text-teal-200">Research only. This report does not change optimizer projections or establish a contest edge.</p></header>
    <section className={panel}><h2 className="text-xl font-bold">Chronological scoring comparison</h2><p className="my-2 text-sm">Recorded WR games, using strictly earlier weeks. The comparator is an eight-game weighted scoring baseline, not the live historical optimizer. Both models use the same method for prior-error ranges. These previously inspected seasons are retrospective diagnostics.</p><div className="grid gap-4 md:grid-cols-2">{Object.entries(report.replay).map(([year,r])=><article key={year} className="rounded-xl bg-slate-50 p-4"><h3 className="font-bold">{year} / {r.n.toLocaleString()} WR games</h3><div className="my-3 space-y-2">{[['Weighted baseline',r.baseline.mae],['Volume/share',r.candidate.mae]].map(([label,value])=><div key={label}><div className="flex justify-between text-sm"><span>{label}</span><strong>{Number(value).toFixed(2)} MAE</strong></div><div className="h-2 rounded bg-slate-200"><div className="h-2 rounded bg-teal-600" style={{width:`${Number(value)/6*100}%`}} /></div></div>)}</div><p className="text-sm">80% interval score: {r.baseline.interval_score80.toFixed(2)} → {r.candidate.interval_score80.toFixed(2)}</p><p className="text-sm">80% interval coverage: {(r.baseline.coverage80*100).toFixed(1)}% → {(r.candidate.coverage80*100).toFixed(1)}%</p><p className="text-sm">Target MAE: {r.baseline.targets_mae.toFixed(3)} → {r.candidate.targets_mae.toFixed(3)}</p><p className="mt-2 text-xs text-slate-500">Lower MAE and interval score are better; target MAE worsened in 2024.</p></article>)}</div></section>
    <section className="rounded-2xl border border-amber-300 bg-amber-50 p-5"><h2 className="font-bold">Availability evidence limits activation</h2><p>{report.historical_pregame_availability_rows} stored injury observations cover the replay seasons. {report.availability_audit.reduce((s,r)=>s+r.n,0).toLocaleString()} observations are available for 2026 as of this audit. Historical tests therefore use no target-week injury or participation information.</p><p className="mt-2">The listed-out scenario below reallocates half of an unavailable player’s known share; it retains the other half as unallocated work. That fraction has not been calibrated. Unknown or stale availability never implies an absence.</p></section>
    <section className={panel}><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-xl font-bold">Frozen pregame research forecasts</h2><label>Team <select className="rounded border p-2" value={team} onChange={e=>setTeam(e.target.value)}>{report.forward.map(f=><option key={f.team}>{f.team}</option>)}</select></label></div><p className="my-2 text-sm">Captured {new Date(report.as_of).toUTCString()} / {stale?'Expired or invalid for current use':`${Math.floor(age)} hours old at page load`}. Static research snapshot, not a live feed. {report.forward.length} teams have matching historical data.</p>
    {forecast&&<><p className="text-sm">Kickoff: {new Date(forecast.kickoff).toUTCString()}{Date.parse(forecast.kickoff)<=viewedAt?' / Game has started; historical view only':''}</p><div className="my-4 grid gap-3 sm:grid-cols-3">{[['Projected pass attempts',forecast.attempts],['Allocatable team targets',forecast.target_budget],['Unallocated after scenario',forecast.unallocated_targets]].map(([label,value])=><div key={label} className="rounded-xl bg-teal-50 p-4"><strong className="block text-2xl">{number(Number(value))}</strong><span className="text-sm">{label}</span></div>)}</div><p className="text-sm">{number(forecast.unmatched_historical_targets)} targets remain attached to historical recipients without a current roster match; they are not assigned to a current receiver. RB and TE shares also consume the budget.</p><div className="my-3 h-3 overflow-hidden rounded bg-slate-200" aria-label="Allocated versus unallocated target budget"><div className="h-full bg-teal-600" style={{width:`${100*(1-forecast.unallocated_targets/Math.max(1,forecast.target_budget))}%`}} /></div><p className="text-xs text-slate-500">Teal: historical recipient allocation, including unmatched recipients. Gray: unallocated targets.</p><p className="my-3 text-sm">Fresh listed-out evidence: {forecast.out_players.map(p=>`${p.name} (${p.status}, ${new Date(p.captured_at).toUTCString()})`).join('; ')||'None established'}. Source: Sleeper roster retrieval, not official game-day confirmation.</p>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><caption className="mb-2 text-left text-xs">Ranges belong to the unadjusted volume/share model. No injury-scenario ranges or lineup percentiles are claimed.</caption><thead className="bg-slate-100"><tr>{['WR / status','History','Baseline targets','Volume targets','Listed-out scenario targets','Baseline DK','Volume DK','Player P10 / P50 / P90'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{forecast.players.map(p=><tr key={p.identity} className="border-b"><td className="p-2 font-semibold">{p.name}<span className="block text-xs font-normal text-slate-500">{p.availability?.status??'Availability unresolved'}</span></td><td>{p.history_games} games</td><td>{number(p.targets_baseline)}</td><td>{number(p.targets_volume)}</td><td>{number(p.targets_if_out)}</td><td>{number(p.fpts_baseline)}</td><td>{number(p.fpts_volume)}</td><td>{number(p.p10)} / {number(p.p50)} / {number(p.p90)}</td></tr>)}</tbody></table></div></>}
    </section><details className={panel}><summary className="cursor-pointer font-semibold">Recipe and provenance</summary><p className="my-2 text-sm">Eight recent games; four-game half-life; at least four recorded player games. DK changes use a capped historical points-per-target proxy, which can include rushing and return production; this is not a complete stat simulator. Residual ranges use earlier WR errors. New players and missing stat rows are outside the scored cohort.</p><ul className="list-disc pl-5 text-sm">{report.limits.map(l=><li key={l}>{l}</li>)}</ul><p className="my-2 break-all text-xs">Snapshot {report.snapshot_digest}</p><p className="break-all text-xs">Recipe {report.recipe_digest}</p><p className="break-all text-xs">Roster evidence {report.roster_evidence_digest}</p>{report.sources.map(s=><p key={s.season} className="my-2 break-all text-xs"><a className="underline" href={s.url}>{s.season} weekly stats</a> / SHA-256 {s.sha256}</p>)}</details>
  </main>;
}
