"use client";
import { calibratedRelease } from "@/lib/nfl-dfs/calibrated-projection";
import type { NflWorkspaceSlate } from "./actions";

export default function CalibratedProjections({ slate, active, onChoose }: { slate: NflWorkspaceSlate | null; active: boolean; onChoose: () => void }) {
  const qualified = slate?.players.filter(p => p.calibrated && !p.isOut) ?? [];
  return <section className="space-y-4 rounded-2xl border border-teal-200 bg-teal-50/50 p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-teal-800">Optimizer projection upgrade · opt-in</p><h2 className="mt-1 text-xl font-bold">Calibrated QB and defense projections</h2></div><button disabled={!qualified.length || active} onClick={onChoose} className="rounded-lg bg-teal-800 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{active ? "Selected for next optimization" : "Use calibrated projections"}</button></div>
    <p className="text-sm text-slate-700">QB workload and historical defense calibration improved both point error and interval quality in our historical comparison. In this separate source, other positions retain the historical baseline because their candidate ranges worsened. Forward validation is pending; this is an experimental source.</p>
    <div className="grid gap-4 sm:grid-cols-2">{(["QB", "DST"] as const).map(position => {
      const evidence = calibratedRelease.positions[position].seasons["2025"];
      const gain = 100 * (1 - evidence.opportunity.mae / evidence.baseline.mae);
      return <div key={position} className="rounded-xl border bg-white p-4"><div className="flex justify-between text-sm"><b>{position} · {evidence.baseline.n} player weeks</b><span>{gain.toFixed(2)}% lower MAE</span></div><div className="mt-3 text-xs text-slate-600">Baseline {evidence.baseline.mae.toFixed(3)} DK points error<div className="mt-1 h-2 rounded bg-slate-300" style={{ width: `${evidence.baseline.mae / 8 * 100}%` }} /></div><div className="mt-2 text-xs text-teal-900">Candidate {evidence.opportunity.mae.toFixed(3)} DK points error<div className="mt-1 h-2 rounded bg-teal-700" style={{ width: `${evidence.opportunity.mae / 8 * 100}%` }} /></div><p className="mt-3 text-xs">80% interval score: {evidence.baseline.intervalScore80.toFixed(2)} → {evidence.opportunity.intervalScore80.toFixed(2)} (lower is better)</p></div>;
    })}</div>
    <p className="text-xs text-slate-600">2023 fit · 2024 selection · 2025 retrospective diagnostic, previously inspected. Market-free recorded-stat cohorts, not contest returns. DST is a historical scoring correction; it is not a workload model.</p>
    {!slate ? <p className="text-sm">Load a salary CSV to compare available pregame forecasts and use them in the optimizer.</p> : <>
      <p className="text-sm"><b>{qualified.length} eligible calibrated players</b> in this slate. Forecasts must match player, position, opponent and salary game date, be under 72 hours old, and precede kickoff. Checked again when generating.</p>
      {slate.warnings.map(w => <p key={w} role="status" className="text-sm text-amber-800">{w}</p>)}
      {qualified.length > 0 && <div className="max-h-80 overflow-auto rounded-lg border bg-white"><table className="w-full min-w-[700px] text-left text-xs"><caption className="p-3 text-left">Player projection changes · calibrated rows only. Baseline here is the same market-free frozen forecast; “Our” in the pool may include environment adjustments.</caption><thead className="sticky top-0 bg-slate-100"><tr>{["Player", "Baseline mean", "New mean", "Change", "Baseline P10 / P90", "New P10 / P50 / P90", "Frozen"].map(h => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{qualified.map(p => { const c = p.calibrated!; return <tr key={p.dkPlayerId} className="border-t"><td className="p-3 font-bold">{p.name}</td><td className="p-3">{c.baselineMean.toFixed(1)}</td><td className="p-3 font-bold text-teal-900">{c.mean.toFixed(1)}</td><td className="p-3">{c.mean - c.baselineMean > 0 ? "+" : ""}{(c.mean - c.baselineMean).toFixed(1)}</td><td className="p-3">{c.baselineP10.toFixed(1)} / {c.baselineP90.toFixed(1)}</td><td className="p-3">{c.p10.toFixed(1)} / {c.p50.toFixed(1)} / {c.p90.toFixed(1)}</td><td className="p-3" title={`Snapshot ${c.snapshotId}`}>{new Date(c.capturedAt).toLocaleString()}</td></tr>; })}</tbody></table></div>}
      <details className="text-xs"><summary className="cursor-pointer font-bold">Fallback audit</summary><ul className="mt-3 space-y-1">{slate.players.filter(p => !p.calibrated).map(p => <li key={p.dkPlayerId}>{p.name}: {p.calibrationReason} {p.ourProj !== null && p.ourProj > 0 ? "Historical baseline available." : "No usable baseline; DK fallback depends on your setting."}</li>)}</ul></details>
    </>}
    <p className="text-xs text-slate-700">Cash uses each selected source’s lower-tail estimate; GPP uses its upper-tail estimate and boom probability. Their sums remain search heuristics, not complete-lineup percentiles. This release does not model injury counterfactuals or add Kelly sizing.</p>
  </section>;
}
