"use client";
import {useState,useTransition} from 'react';
import {freezeNflBenchmark,loadNflBenchmarks,previewNflTargetRedistribution,type NflWorkspaceSlate} from './actions';
import type {Competitor} from '@/lib/nfl-dfs/competitor-benchmark';
const points=(x:number|null)=>x===null?'Pending':x.toFixed(2);
function download(name:string,value:unknown) {const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}

export default function CompetitorPanel({slate}:{slate:NflWorkspaceSlate}) {
  const [source,setSource]=useState<Competitor>('fantasypros'),[message,setMessage]=useState(''),[pending,startTransition]=useTransition();
  const [reports,setReports]=useState<Awaited<ReturnType<typeof loadNflBenchmarks>>|null>(null);
  const [team,setTeam]=useState(slate.teams[0]??'');
  const [scenario,setScenario]=useState<Extract<Awaited<ReturnType<typeof previewNflTargetRedistribution>>,{ok:true}>['result']|null>(null);
  function refresh(){startTransition(async()=>{try{setReports(await loadNflBenchmarks(slate.uploadId));setMessage('Saved benchmarks refreshed from completed-game results.');}catch{setMessage('Saved benchmarks or result data could not be loaded. This is not a zero-result report.');}});}
  return <section className="space-y-4 rounded-xl border border-indigo-200 bg-white p-5" aria-label="Competitor benchmark">
    <h2 className="text-lg font-bold">Our model vs competitors</h2>
    <p className="text-sm">Import a same-week DraftKings FantasyPros or LineStar projection CSV in Source comparison, then freeze a pregame benchmark. Each saved record retains both sources, salary, roster and injury evidence. Results compare the same players; later imports cannot overwrite a freeze.</p>
    <div className="flex flex-wrap gap-3"><select aria-label="Benchmark competitor" className="rounded border p-2" value={source} disabled={pending} onChange={e=>setSource(e.target.value as Competitor)}><option value="fantasypros">FantasyPros</option><option value="linestar">LineStar</option></select>
      <button disabled={pending} className="rounded bg-indigo-800 px-4 py-2 text-white disabled:opacity-40" onClick={()=>startTransition(async()=>{try{const r=await freezeNflBenchmark(slate.uploadId,source);setMessage(r.ok?`Saved ${r.paired} paired players. Benchmark ${r.digest.slice(0,12)}.`:r.error);if(r.ok)setReports(await loadNflBenchmarks(slate.uploadId));}catch{setMessage('Unable to freeze the benchmark. Refresh the slate and try again.');}})}>Freeze pregame benchmark</button>
      <button disabled={pending} className="rounded border px-3 py-2" onClick={refresh}>Refresh report card</button></div>
    {message&&<p role="status" className="text-sm text-indigo-900">{message}</p>}
    <p className="text-xs text-slate-600">Our model must be under 72 hours old; competitor imports under 24 hours. All paired games must be unstarted and match salary kickoff times. Imported scoring format and week are user-supplied, not independently verified. Imported-file publication time is unknown; this proves pregame capture, not synchronized provider updates. Top-10 value picks use projected points per $1,000. Identical five-lineup Classic searches use means, no fallback, no ownership adjustment and no randomness. Payouts and calibrated ceiling probabilities require additional evidence.</p>
    {reports?.length===0&&<p>No saved benchmarks for this slate yet. Missing competitor data is not a win or loss.</p>}
    {reports?.map(r=><article key={r.digest} className="space-y-3 rounded-lg bg-slate-50 p-4"><h3 className="font-semibold">{r.snapshot.source} · captured {r.snapshot.capturedAt}</h3><p className="text-sm">{r.grade.paired}/{r.snapshot.rows.length} paired outcomes · {r.grade.pending} pending or unresolved · {r.snapshot.exclusions.length} excluded at freeze. Our model as of {r.snapshot.modelAsOf}.</p>
      <div className="overflow-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{['Source','Mean error ↓','Bias','Top 10: 3× hits','Top 10: 4× hits','Mean / best lineup'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{r.grade.sources.map(s=><tr key={s.source}><td className="p-2">{s.source==='our'?'Our historical model':r.snapshot.source}</td><td>{points(s.mae)}</td><td>{points(s.bias)}</td>{s.salaryHits.map(h=><td key={h.multiple}>{h.n?`${h.hits}/${h.n}`:'Pending'} ({s.selectedScored}/{s.selected} scored)</td>)}<td>{points(s.meanLineup)} / {points(s.bestLineup)} ({s.scoredLineups}/{s.lineups})</td></tr>)}</tbody></table></div>
      {r.grade.sources.map(s=><div key={s.source} className="text-xs"><span>{s.source==='our'?'Our model':r.snapshot.source}: 3× hits among scored top-value picks</span><div className="mt-1 h-2 rounded bg-slate-200"><div className="h-full rounded bg-indigo-600" style={{width:`${s.selectedScored?100*s.salaryHits[0].hits/s.selectedScored:0}%`}}/></div></div>)}
      {r.snapshot.lineupWarnings.map(w=><p key={w} className="text-xs text-amber-900">{w}</p>)}
      <details><summary className="cursor-pointer text-sm">Coverage and source evidence</summary><p className="my-2 text-xs">No missing/DNP score is inferred as zero. Grades use the latest exact result revision for completed games. These individual snapshots are not independent samples and are not aggregated into a season claim.</p><ul className="max-h-40 overflow-auto text-xs">{r.snapshot.exclusions.map((x,i)=><li key={i}>{x.name}: {x.reason}</li>)}</ul></details>
      <button className="text-sm text-indigo-800 underline" onClick={()=>download(`nfl-benchmark-${r.digest.slice(0,12)}.json`,r)}>Download frozen inputs and current grade</button></article>)}
    <div className="space-y-3 border-t pt-4"><h3 className="font-semibold">Experimental: redistribute one absent receiver’s targets</h3>
      <p className="text-sm">Uses the full saved roster, including RBs and players outside the salary CSV. Exactly one officially inactive WR/TE and an unchanged, resolved starting QB are required. Half the missing player’s prior target share is distributed among eligible returning pass catchers; the rest stays reserved. This fixed hypothesis changes no optimizer points.</p>
      <div className="flex gap-3"><select disabled={pending} aria-label="Redistribution team" className="rounded border p-2" value={team} onChange={e=>{setTeam(e.target.value);setScenario(null);}}>{slate.teams.map(t=><option key={t}>{t}</option>)}</select><button disabled={pending} className="rounded border px-3 py-2" onClick={()=>{setScenario(null);startTransition(async()=>{try{const r=await previewNflTargetRedistribution(slate.uploadId,team);if(r.ok){setScenario(r.result);setMessage('Experimental target allocation ready.');}else setMessage(r.error);}catch{setMessage('Full-roster target scenario could not be loaded.');}});}}>Check full roster and preview</button></div>
      {scenario&&<><p className="text-sm">{scenario.targetBudget.toFixed(1)} team targets · {scenario.redistributedTargets.toFixed(1)} reassigned · {scenario.reservedTargets.toFixed(1)} reserved. Coaching continuity: {scenario.continuity}.</p><div className="max-h-72 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Player</th><th>Prior reference</th><th>Scenario targets</th><th>Added</th></tr></thead><tbody>{scenario.rows.map(p=><tr key={p.id} className="border-t"><td className="p-2">{p.name} · {p.position}{!p.eligible?' · unallocated':''}</td><td>{p.referenceTargets.toFixed(1)}</td><td>{p.targets.toFixed(1)}</td><td>{p.gain.toFixed(1)}</td></tr>)}</tbody></table></div><p className="text-xs">{scenario.limits.join(' ')}</p><button className="text-sm text-indigo-800 underline" onClick={()=>download(`nfl-target-allocation-${scenario.team}.json`,scenario)}>Download target scenario and roster evidence</button></>}
    </div>
  </section>;
}
