"use client";

import { useMemo, useState } from "react";
import { Cell, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { Activity, Boxes, CircleDollarSign, GitBranch, ShieldCheck, Sparkles } from "lucide-react";
import type { NflGeneratedLineup, NflProjectionSource } from "./nfl-optimizer";
import { averagePairwiseUnique, buildLineupInsight, lineupOverlap } from "@/lib/nfl-dfs/lineup-insights";

const PALETTE = ["#2563eb", "#7c3aed", "#059669", "#ea580c", "#0891b2", "#db2777", "#4f46e5", "#65a30d", "#dc2626"];
const TONES = { ceiling: "border-violet-200 bg-violet-50 text-violet-900", floor: "border-blue-200 bg-blue-50 text-blue-900", correlation: "border-emerald-200 bg-emerald-50 text-emerald-900", value: "border-amber-200 bg-amber-50 text-amber-950", diversity: "border-cyan-200 bg-cyan-50 text-cyan-950", source: "border-slate-200 bg-slate-50 text-slate-900" } as const;

export default function NflLineupVisualizations({ lineups, mode, projectionSource }: { lineups: NflGeneratedLineup[]; mode: "cash" | "gpp"; projectionSource: NflProjectionSource }) {
  const [selectedNumber, setSelectedNumber] = useState(lineups[0]?.lineupNumber ?? 1);
  const selected = lineups.find((lineup) => lineup.lineupNumber === selectedNumber) ?? lineups[0];
  const insight = useMemo(() => buildLineupInsight(selected, lineups, mode, projectionSource), [selected, lineups, mode, projectionSource]);
  const scatter = lineups.map((lineup) => ({ number: lineup.lineupNumber, floor: Number(lineup.floorFpts.toFixed(2)), ceiling: Number(lineup.ceilingFpts.toFixed(2)), projection: Number(lineup.projectedFpts.toFixed(2)), salaryLeft: 50000 - lineup.totalSalary }));
  const averageFloor = lineups.reduce((sum, lineup) => sum + lineup.floorFpts, 0) / lineups.length;
  const averageCeiling = lineups.reduce((sum, lineup) => sum + lineup.ceilingFpts, 0) / lineups.length;
  const maxPlayerProjection = Math.max(...selected.slots.map((entry) => entry.projection));
  const gameColor = new Map(insight.gameCounts.map((game, index) => [game.game, PALETTE[index % PALETTE.length]]));
  const displayed = lineups.slice(0, 20);

  return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
    <div className="border-b border-slate-200 bg-gradient-to-r from-slate-950 to-blue-950 p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-cyan-300"><Sparkles className="h-4 w-4" />Portfolio intelligence</div><h2 className="mt-1 text-xl font-black">Why these lineups fit the objective</h2><p className="mt-1 text-xs text-slate-300">Derived from the saved optimizer output—no narrative model and no hidden inputs.</p></div><select value={selected.lineupNumber} onChange={(event) => setSelectedNumber(Number(event.target.value))} className="min-h-10 rounded-lg border border-slate-600 bg-slate-900 px-3 text-sm font-bold text-white">{lineups.map((lineup) => <option key={lineup.lineupNumber} value={lineup.lineupNumber}>Inspect lineup {lineup.lineupNumber}</option>)}</select></div></div>
    <div className="grid gap-4 p-4 md:grid-cols-4"><Summary icon={<Activity />} label={mode === "gpp" ? "Ceiling rank" : "Floor rank"} value={`#${mode === "gpp" ? insight.ceilingRank : insight.floorRank} of ${lineups.length}`} /><Summary icon={<CircleDollarSign />} label="Salary efficiency" value={`${insight.valuePerThousand.toFixed(2)} pts/$1K`} /><Summary icon={<Boxes />} label="Games represented" value={String(insight.gameCounts.length)} /><Summary icon={<GitBranch />} label="Portfolio separation" value={`${averagePairwiseUnique(lineups).toFixed(1)} avg unique`} /></div>
    <div className="grid gap-5 border-t border-slate-100 p-4 xl:grid-cols-2">
      <div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><div><h3 className="font-bold">Floor / ceiling frontier</h3><p className="text-xs text-slate-500">Upper-right lineups preserve floor while adding upside. Dot size reflects projection.</p></div><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-800">CLICK A DOT</span></div><div className="mt-3 h-72"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 12, right: 16, bottom: 12, left: 0 }}><XAxis type="number" dataKey="floor" name="Floor" domain={["dataMin - 2", "dataMax + 2"]} tick={{ fontSize: 10 }} label={{ value: "Floor", position: "insideBottom", offset: -7, fontSize: 10 }} /><YAxis type="number" dataKey="ceiling" name="Ceiling" domain={["dataMin - 2", "dataMax + 2"]} tick={{ fontSize: 10 }} width={42} /><ZAxis type="number" dataKey="projection" range={[65, 180]} /><ReferenceLine x={averageFloor} stroke="#94a3b8" strokeDasharray="4 4" /><ReferenceLine y={averageCeiling} stroke="#94a3b8" strokeDasharray="4 4" /><Tooltip cursor={{ strokeDasharray: "3 3" }} content={({ active, payload }) => active && payload?.[0] ? <div className="rounded-lg border bg-white p-2 text-xs shadow-lg"><b>Lineup {String(payload[0].payload.number)}</b><div>Floor {Number(payload[0].payload.floor).toFixed(1)}</div><div>Ceiling {Number(payload[0].payload.ceiling).toFixed(1)}</div><div>${Number(payload[0].payload.salaryLeft).toLocaleString()} unspent</div></div> : null} /><Scatter data={scatter} onClick={(_, index) => setSelectedNumber(scatter[index].number)}>{scatter.map((point) => <Cell key={point.number} fill={point.number === selected.lineupNumber ? "#f97316" : "#2563eb"} stroke={point.number === selected.lineupNumber ? "#7c2d12" : "#1e3a8a"} strokeWidth={point.number === selected.lineupNumber ? 3 : 1} />)}</Scatter></ScatterChart></ResponsiveContainer></div></div>
      <div className="rounded-xl border border-slate-200 p-4"><h3 className="font-bold">Lineup anatomy</h3><p className="text-xs text-slate-500">Point contribution by roster slot. Color groups players from the same game.</p><div className="mt-4 space-y-2">{selected.slots.map((entry) => <div key={entry.slot} className="grid grid-cols-[42px_minmax(100px,1fr)_minmax(100px,1.3fr)_48px] items-center gap-2 text-xs"><b className="text-slate-500">{entry.slot}</b><div className="truncate"><b>{entry.player.name}</b><span className="ml-1 text-slate-400">{entry.player.team}</span></div><div className="h-5 overflow-hidden rounded bg-slate-100"><div className="h-full rounded" style={{ width: `${Math.max(4, entry.projection / maxPlayerProjection * 100)}%`, backgroundColor: gameColor.get(entry.player.gameKey ?? "Unmapped game") }} /></div><b className="text-right tabular-nums">{entry.projection.toFixed(1)}</b></div>)}</div><div className="mt-4 flex flex-wrap gap-2">{insight.gameCounts.map((game) => <span key={game.game} className="inline-flex items-center gap-1.5 rounded-full border px-2 py-1 text-[10px] font-bold"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: gameColor.get(game.game) }} />{game.game}: {game.players} players / {game.projection.toFixed(1)} pts</span>)}</div></div>
    </div>
    <div className="grid gap-5 border-t border-slate-100 p-4 xl:grid-cols-[1.1fr_.9fr]">
      <div><h3 className="font-bold">Construction thesis</h3><p className="text-xs text-slate-500">Mechanical explanations of the objective, correlation, value, diversity, and source coverage.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{insight.reasons.map((reason) => <div key={reason.label} className={`rounded-lg border p-3 ${TONES[reason.tone]}`}><div className="text-xs font-black uppercase tracking-wide">{reason.label}</div><p className="mt-1 text-xs leading-relaxed opacity-80">{reason.detail}</p></div>)}</div></div>
      <div><h3 className="font-bold">Portfolio overlap fingerprint</h3><p className="text-xs text-slate-500">Shared players versus lineup {selected.lineupNumber}. Darker means more overlap; orange is the selected lineup.</p><div className="mt-3 grid grid-cols-5 gap-2 sm:grid-cols-10">{displayed.map((lineup) => { const overlap = lineupOverlap(selected, lineup); return <button key={lineup.lineupNumber} onClick={() => setSelectedNumber(lineup.lineupNumber)} title={`${overlap} shared players`} className={`aspect-square rounded-lg border text-[10px] font-black ${lineup.lineupNumber === selected.lineupNumber ? "border-orange-600 bg-orange-500 text-white" : "border-blue-200 text-blue-950"}`} style={lineup.lineupNumber === selected.lineupNumber ? undefined : { backgroundColor: `rgba(37,99,235,${.08 + overlap / selected.playerIds.length * .72})` }}>{lineup.lineupNumber}<span className="block text-[8px] font-medium">{overlap}/{selected.playerIds.length}</span></button>; })}</div>{lineups.length > 20 ? <p className="mt-2 text-[10px] text-slate-400">Showing the first 20 of {lineups.length}; portfolio separation above uses all lineups.</p> : null}<div className="mt-4 flex items-start gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-950"><ShieldCheck className="h-4 w-4 shrink-0" /><span><b>Audit note:</b> each explanation is recomputed from the immutable lineup snapshot and the selected objective. It does not assert that the lineup will win.</span></div></div>
    </div>
  </section>;
}

function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3"><span className="text-blue-700 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><div className="text-[9px] font-bold uppercase tracking-wide text-slate-500">{label}</div><div className="text-sm font-black text-slate-950">{value}</div></div></div>; }
