'use client';
import {useMemo,useState} from 'react';
import type {NflWorkspaceSlate} from './actions';
import type {NflOptimizerSettings} from './nfl-optimizer';
import {prepareProjectionAudits,type SituationSettings,type TeamAssumption} from '@/lib/nfl-dfs/projection-audit';
import {benchmarkTeam} from '@/lib/nfl-dfs/competitor-benchmark';
import type {RoleSettings} from '@/lib/nfl-dfs/role-allocation';

export function previewAudits(slate:NflWorkspaceSlate,settings:NflOptimizerSettings) {
  return prepareProjectionAudits(slate.players,slate.situationTeams??[],settings.workloadPositions,settings.situations,Date.now());
}
function download(name:string,value:unknown) {
  const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);
}
const pts=(v:number|null|undefined)=>v==null?'—':v.toFixed(2);
export default function ProjectionAuditPanel({slate,settings,onChange}:{slate:NflWorkspaceSlate|null;settings:NflOptimizerSettings;onChange:(s:SituationSettings)=>void}) {
  const [id,setId]=useState(''),[team,setTeam]=useState(''),[profile,setProfile]=useState<TeamAssumption['profile']>('all'),[reason,setReason]=useState(''),[passing,setPassing]=useState(1),[roles,setRoles]=useState<RoleSettings>({}),[error,setError]=useState('');
  const preview=useMemo(()=>{try{return {players:slate?previewAudits(slate,settings):[],error:''};}catch(e){return {players:[],error:e instanceof Error?e.message:'Preview unavailable.'};}},[slate,settings]);
  const players=preview.players.filter(p=>p.projectionAudit?.final!=null).sort((a,b)=>((b.projectionAudit!.final??0)-(b.ourProj??0))-((a.projectionAudit!.final??0)-(a.ourProj??0)));
  const selected=players.find(p=>String(p.dkPlayerId)===id)??players[0],audit=selected?.projectionAudit;
  const teams=(slate?.situationTeams??[]).filter(t=>slate?.teams.some(s=>benchmarkTeam(s)===t.team));
  const chosen=teams.find(t=>t.team===team);
  const active=settings.projectionSource==='workload';
  return <section className="space-y-4 rounded-xl border border-teal-200 bg-teal-50/40 p-5" aria-label="Projection explanation">
    <h2 className="text-xl font-bold">Why is this projection different?</h2>
    <p className="text-sm">{active?'These adjustments feed the next workload optimizer run.':'Preview for the experimental workload source. Select Position workload to use these estimates in the optimizer.'} Every change below is measured from our historical projection, not the player’s raw fantasy average.</p>
    <label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={settings.situations?.enabled??false} onChange={e=>onChange({enabled:e.target.checked,teams:settings.situations?.teams??{}})}/>Connect verified injury evidence and reviewed situation assumptions</label>
    <p className="text-xs">A verified inactive WR/TE can release targets under the explicit 50% redistribution hypothesis. Questionable does not mean out. Changed QBs, rookies and arrivals require supported role evidence; unknown effects receive no automatic boost. Adjusted ranges are experimental shifts of existing player ranges.</p>
    {preview.error&&<p role="alert" className="text-red-800">{preview.error}</p>}
    {audit&&selected&&<>
      <label className="block text-sm font-semibold">Inspect player <select className="ml-2 max-w-full rounded border bg-white p-2" value={selected.dkPlayerId} onChange={e=>setId(e.target.value)}>{players.map(p=><option key={p.dkPlayerId} value={p.dkPlayerId}>{p.name} · {p.position} · {pts((p.projectionAudit!.final??0)-(p.ourProj??0))} pts vs baseline{p.isOut?' · excluded':''}</option>)}</select></label>
      <div className="grid gap-4 rounded-lg bg-white p-4 sm:grid-cols-3"><div><p className="text-sm">Historical baseline</p><strong className="text-2xl">{pts(audit.baseline)}</strong></div><div><p className="text-sm">Net change</p><strong className="text-2xl">{audit.baseline==null?'—':pts((audit.final??0)-audit.baseline)}</strong></div><div><p className="text-sm">{audit.excluded?'Excluded from optimization':'Workload estimate'}</p><strong className="text-2xl">{pts(audit.final)}</strong></div></div>
      <div className="space-y-2" aria-label="Baseline and adjusted point comparison">{[['Baseline',audit.baseline],['Adjusted',audit.final]].map(([label,value])=><div key={String(label)} className="flex items-center gap-2 text-sm"><span className="w-20">{label}</span><div className="h-5 rounded bg-teal-700" style={{width:`${Math.max(0,Number(value??0))/Math.max(1,audit.baseline??0,audit.final??0)*65}%`}}/><span>{pts(value as number|null)}</span></div>)}</div>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Reason</th><th>Point change</th><th>Evidence / calculation</th></tr></thead><tbody>{audit.steps.map((s,i)=><tr className="border-t" key={i}><td className="p-2 align-top font-semibold">{s.label}<div className="text-xs font-normal">{s.status==='applied'?'Applied':'No point adjustment'}</div></td><td className="p-2 align-top">{s.points>0?'+':''}{pts(s.points)}</td><td className="p-2">{s.reason}{s.calculation&&<div className="mt-1 font-mono text-xs">({s.calculation.after.toFixed(3)} − {s.calculation.before.toFixed(3)}) {s.calculation.unit} × {s.calculation.pointsPerUnit.toFixed(4)} pts = {s.points.toFixed(4)}</div>}</td></tr>)}</tbody></table></div>
      <p className="text-xs">{audit.rangeMethod}</p><p className="text-xs">Baseline: {slate?.modelVersion??'unknown'} · {slate?.modelAsOf??'undated'} · Run {slate?.projectionRunId??'unlinked'}. Rate inputs include player sample size and shrinkage toward position averages; see the downloadable audit.</p>
      <button className="rounded border bg-white px-3 py-2 text-sm" onClick={()=>download('nfl-projection-explanations.json',{preview:true,generatedAt:new Date().toISOString(),uploadId:slate?.uploadId,baselineSource:{runId:slate?.projectionRunId,asOf:slate?.modelAsOf,model:slate?.modelVersion},settings,teams:slate?.situationTeams,players:preview.players.map(p=>({dkPlayerId:p.dkPlayerId,name:p.name,audit:p.projectionAudit}))})}>Download explanation and evidence</button>
    </>}
    <p className="text-xs">Saved team assumptions: {Object.keys(settings.situations?.teams??{}).join(", ")||"none"}. <button className="underline" onClick={()=>{onChange({enabled:settings.situations?.enabled??true,teams:{}});setRoles({});setProfile("all");setPassing(1);setReason("");setError("");}}>Clear all assumptions</button></p>
    <details className="rounded border bg-white p-3"><summary className="cursor-pointer font-semibold">Reviewed team and player assumptions</summary><p className="my-2 text-sm">Use this for a documented scheme, role or partial-injury assumption. Selecting a 2025 game-script profile keeps full-game play count fixed and changes run/pass mix. Passing efficiency scales expected passing/receiving scoring, not targets. These are your assumptions, not provider injury facts.</p>
      <label className="mr-3 text-sm">Team <select className="rounded border p-2" value={team} onChange={e=>{const key=e.target.value;setTeam(key);const saved=settings.situations?.teams[key];setProfile(saved?.profile??'all');setPassing(saved?.passingEfficiency??1);setReason(saved?.reason??'');setRoles(saved?.roles??{});setError('');}}><option value="">Choose team</option>{teams.map(t=><option key={t.team}>{t.team}</option>)}</select></label>
      {chosen&&<div className="mt-3 space-y-3"><p className="text-xs">Coaching: {chosen.continuity}. Snapshot {chosen.capturedAt}. Current QB: {chosen.members.find(m=>m.identity===chosen.currentQb)?.name??'unresolved'}.</p><label className="mr-3 text-sm">2025 profile <select className="rounded border p-2" value={profile} onChange={e=>setProfile(e.target.value as TeamAssumption['profile'])}>{['all','neutral','leading','trailing'].map(p=><option key={p}>{p}</option>)}</select></label><label className="text-sm">Passing efficiency <input aria-label="Passing efficiency multiplier" type="number" min="0.5" max="1.5" step="0.01" value={passing} onChange={e=>setPassing(Number(e.target.value))} className="w-24 rounded border p-2"/> ×</label>
        <label className="block text-sm">Reason and evidence (required)<textarea className="block w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain the role/scheme/injury assumption and cite its source." maxLength={2000}/></label>
        <details><summary className="cursor-pointer text-sm">Full-roster target and carry shares</summary><p className="text-xs">Enter percentages, not counts. Blank retains the same-team reference; explicit zero removes a share. Include reductions for other players when raising a role. Shares across the full roster cannot exceed 100%. Unknown baseline roles cannot yet be converted to point deltas.</p><div className="max-h-64 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Player</th><th>Targets %</th><th>Carries %</th></tr></thead><tbody>{chosen.members.filter(m=>['QB','RB','WR','TE','FB'].includes(m.position)).map(m=><tr key={m.id} className="border-t"><td>{m.name} · {m.position} · {m.availability.status}{m.rookie?' · rookie':m.new_team?' · arrival':''}</td>{(['targets','carries'] as const).map(field=><td key={field}><input aria-label={`${m.name} ${field} share percent`} className="w-24 border p-1" type="number" min="0" max="100" step="0.1" placeholder={((field==='targets'?m.prior_target_share:m.prior_carry_share)??0)*100+''} value={roles[m.id]?.[field]===undefined?'':roles[m.id][field]!*100} onChange={e=>setRoles(prev=>{const next={...prev,[m.id]:{...prev[m.id]}};if(e.target.value==='')delete next[m.id][field];else next[m.id][field]=Number(e.target.value)/100;if(!Object.keys(next[m.id]).length)delete next[m.id];return next;})}/></td>)}</tr>)}</tbody></table></div></details>
        <button className="rounded bg-teal-800 px-3 py-2 text-white" onClick={()=>{const next={enabled:true,teams:{...settings.situations?.teams,[team]:{profile,roles,reason,passingEfficiency:passing}}};try{if(slate)previewAudits(slate,{...settings,situations:next});onChange(next);setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid assumptions.');}}}>Apply reviewed assumption to next workload run</button>
        <button className="ml-2 rounded border px-3 py-2" onClick={()=>{const next={...settings.situations?.teams};delete next[team];onChange({enabled:settings.situations?.enabled??true,teams:next});setProfile('all');setPassing(1);setRoles({});setReason('');setError('');}}>Clear this team’s assumption</button>
      </div>}{error&&<p role="alert" className="mt-2 text-red-800">{error}</p>}
    </details>
  </section>;
}
