"use client";
import {previewAudits} from './projection-audit-panel';
import {useState,useTransition} from 'react';
import {compareNflWorkload,type NflWorkspaceSlate} from './actions';
import type {NflOptimizerSettings} from './nfl-optimizer';
import {WORKLOAD_POSITIONS,LEGACY_WORKLOAD_POSITIONS,selectedWorkload,workloadSourceReason,type WorkloadPositions} from '@/lib/nfl-dfs/workload-selection';
import {calibratedRelease} from '@/lib/nfl-dfs/calibrated-projection';
import benchmark from '@/data/nfl-volume-benchmark.json';
const descriptions={QB:'Recent pass-attempt calibration',RB:'Recent carries + targets calibration',WR:'Team pass volume and target shares',TE:'Recent target calibration'};
const points=(n:number|null|undefined)=>n==null?'—':n.toFixed(1);
export default function WorkloadProjections({slate,active,onChoose,settings,onPositionsChange}:{slate:NflWorkspaceSlate|null;active:boolean;onChoose:()=>void;settings:NflOptimizerSettings;onPositionsChange:(positions:WorkloadPositions)=>void}) {
  const [pending,startTransition]=useTransition(),[error,setError]=useState('');
  const [comparison,setComparison]=useState<Awaited<ReturnType<typeof compareNflWorkload>>|null>(null);
  const controls=settings.workloadPositions??LEGACY_WORKLOAD_POSITIONS;
  let players=slate?.players??[];
  try {if(slate)players=previewAudits(slate,settings);}catch {/* The explanation panel displays the invalid assumption and server generation rejects it. */}
  const eligible=players.filter(p=>selectedWorkload(p,controls)&&!p.isOut&&!settings.excludedPlayerIds.includes(p.dkPlayerId));
  return <section className="space-y-4 rounded-xl border border-indigo-200 bg-indigo-50/40 p-5" aria-label="Workload optimizer source">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Position workload → optimizer</h2><button disabled={!eligible.length||active} onClick={onChoose} className="rounded bg-indigo-800 px-4 py-3 text-white disabled:opacity-40">{active?'Workload selected':'Use experimental position workload'}</button></div>
    <p className="text-sm">Choose which positions use candidate points and ranges in generated lineups. Disabled positions or unavailable candidates retain labeled historical projections, then optional DK fallback. QBs require current starting-role evidence. The historical source remains the app default.</p>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{WORKLOAD_POSITIONS.map(pos=>{
      const count=players.filter(p=>!p.isOut&&!settings.excludedPlayerIds.includes(p.dkPlayerId)&&(pos==='WR'?p.workload:p.position===pos&&p.positionWorkload)).length;
      const evidence=pos==='WR'?null:calibratedRelease.positions[pos].seasons['2025'];
      const oldMean=evidence?.baseline.mae??benchmark.seasons['2025'].production.mae,newMean=evidence?.opportunity.mae??benchmark.seasons['2025'].candidate.mae;
      const oldRange=evidence?.baseline.intervalScore80??benchmark.seasons['2025'].production.interval80,newRange=evidence?.opportunity.intervalScore80??benchmark.seasons['2025'].candidate.interval80;
      return <article className="space-y-2 rounded border bg-white p-3" key={pos}><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={controls[pos]} onChange={e=>onPositionsChange({...controls,[pos]:e.target.checked})} aria-label={`Enable ${pos} workload`}/>{pos}</label><p className="text-xs">{descriptions[pos]}</p><p className="text-sm">{count} eligible candidates · {controls[pos]?'Enabled':'Historical selected'}</p><p className="text-xs">2025 point error: {oldMean.toFixed(2)} → {newMean.toFixed(2)}</p><div className="h-2 rounded bg-slate-200" aria-label={`${pos} relative point error`}><div className="h-full rounded bg-indigo-600" style={{width:`${Math.min(100,100*newMean/oldMean)}%`}}/></div><p className={`text-xs ${newRange>oldRange?'text-amber-900':'text-teal-800'}`}>Range error: {oldRange.toFixed(2)} → {newRange.toFixed(2)} ({newRange>oldRange?'worse':'better'})</p></article>;
    })}</div>
    <p className="text-sm">{eligible.length} candidates enabled and available. QB and WR start enabled within this experimental source; RB and TE require their own switches. Situation adjustments and their evidence are shown in the explanation panel. QB/RB/TE use saved historical-opportunity calibration, not the full team-budget simulator.</p>
    <p className="text-xs text-slate-600">Previously inspected 2025 cohorts differ by position; lower errors are better. Production-algorithm replay excluded market inputs. No verified historical salary pools support a lineup replay. These results do not establish tournament returns. Player tail sums are search heuristics, not lineup percentiles.</p>
    <details><summary className="cursor-pointer">Player sources, changes and fallback reasons</summary><div className="max-h-96 overflow-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr><th>Player</th><th>{active?'Source for next run':'Source if workload selected'}</th><th>Opportunity reference</th><th>Historical points</th><th>Candidate points</th><th>Candidate P10 / P90</th></tr></thead><tbody>{players.map(p=>{const candidate=selectedWorkload(p,controls);const reason=settings.excludedPlayerIds.includes(p.dkPlayerId)?'Manually excluded':workloadSourceReason(p,controls,settings.allowDkFallback);return <tr className="border-t" key={p.dkPlayerId}><td className="p-2">{p.name} · {p.position}</td><td className="p-2 text-xs">{reason}</td><td>{p.position==='WR'&&p.workload?`${points(p.workload.targets)} projected targets`:p.positionWorkload?.priorOpportunity!=null?`${points(p.positionWorkload.priorOpportunity)} prior opportunities`:'—'}</td><td>{points(p.ourProj)}</td><td>{points(candidate?.mean)}</td><td>{points(candidate?.p10)} / {points(candidate?.p90)}</td></tr>;})}</tbody></table></div></details>
    <button disabled={!eligible.length||pending} className="rounded border bg-white px-4 py-2 disabled:opacity-40" onClick={()=>{if(!slate)return;setError('');startTransition(async()=>{try{setComparison(await compareNflWorkload(slate.uploadId,settings));}catch(e){setError(e instanceof Error?e.message:'Comparison failed.');}});}}>Generate matched comparison</button>
    <p className="text-xs">Uses your position switches and portfolio controls, up to five lineups per source, and zero randomness. Saves both runs from one player snapshot for review after the slate. QB/RB/TE candidates refresh through the daily shadow forecast; WR uses the dated report. All candidates expire after 72 hours or kickoff.</p>
    {error&&<p role="alert">{error}</p>}
    {comparison&&<div className="space-y-2 rounded bg-white p-3"><p>{comparison.note}</p><p className="text-sm">Compared {comparison.comparedAt}. Enabled positions: {WORKLOAD_POSITIONS.filter(p=>(comparison.settings.workloadPositions??LEGACY_WORKLOAD_POSITIONS)[p]).join(', ')}. {comparison.excludedFromComparison} players excluded from the common pregame pool. This result retains its saved controls; generate again after changing them.</p>{(['baseline','candidate'] as const).map(source=>{const r=comparison[source];return <div key={source}>{r.result.warnings.map(w=><p key={w} className="text-xs text-amber-900">{w}</p>)}<b>{source==='baseline'?'Historical':'Position workload'}: {r.result.lineups.length} lineups saved</b><p className="text-xs">Run {r.runId}</p>{r.result.lineups.map(l=><p className="text-sm" key={l.lineupNumber}>#{l.lineupNumber}: {l.slots.map(s=>`${s.player.name} (${s.projectionSource==='workload'?s.player.position+' workload':s.projectionSource==='our_fallback'?'historical':s.projectionSource})`).join(', ')} · ${l.totalSalary.toLocaleString()} · {l.projectedFpts.toFixed(1)} projected points</p>)}</div>;})}<button className="text-indigo-800 underline" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(comparison,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='nfl-workload-comparison.json';a.click();URL.revokeObjectURL(url);}}>Download comparison and frozen inputs</button></div>}
  </section>;
}
