"use client";
import {useState,useTransition} from 'react';
import type {NflWorkspaceSlate} from './actions';
import {compareNflWorkload} from './actions';
import type {NflOptimizerSettings} from './nfl-optimizer';
import benchmark from '@/data/nfl-volume-benchmark.json';

export default function WorkloadProjections({slate,active,onChoose,settings}:{slate:NflWorkspaceSlate|null;active:boolean;onChoose:()=>void;settings:NflOptimizerSettings}) {
  const [pending,startTransition]=useTransition(),[error,setError]=useState('');
  const [comparison,setComparison]=useState<Awaited<ReturnType<typeof compareNflWorkload>>|null>(null);
  const players=slate?.players.filter(p=>p.workload&&!p.isOut)??[];
  return <section className="space-y-4 rounded-xl border border-indigo-200 bg-indigo-50/40 p-5" aria-label="Workload optimizer source">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">WR workload → optimizer</h2><button disabled={!players.length||active} onClick={onChoose} className="rounded bg-indigo-800 px-4 py-3 text-white disabled:opacity-40">{active?'Workload selected':'Use experimental WR workload'}</button></div>
    <p className="text-sm">{players.length} eligible WR forecasts feed projected points and player P10/P90 directly into lineup generation. Current starter evidence is required for QBs. Other eligible players retain the historical source, with DK fallback only if enabled. This source uses unadjusted targets; the separate injury-redistribution scenario is excluded. RB carry projections are not activated by this release.</p>
    <div className="grid gap-3 sm:grid-cols-2">{Object.entries(benchmark.seasons).map(([year,s])=><div className="rounded border bg-white p-3" key={year}><b>{year} · {s.n} paired WR games</b><p className="text-sm">Point error: {s.production.mae.toFixed(2)} → {s.candidate.mae.toFixed(2)} (lower is better)</p><div className="mt-2 h-2 rounded bg-slate-200"><div className="h-full rounded bg-indigo-600" style={{width:`${100*s.candidate.mae/s.production.mae}%`}}/></div><p className="mt-2 text-sm text-amber-900">Range error: {s.production.interval80.toFixed(2)} → {s.candidate.interval80.toFixed(2)} (worse)</p></div>)}</div>
    <p className="text-xs text-slate-600">Previously inspected seasons, production-algorithm replay with market inputs disabled. No verified historical salary mappings for a lineup replay. These results do not establish tournament returns. Player tail sums remain optimizer heuristics, not lineup percentiles.</p>
    <details><summary className="cursor-pointer">Player changes and coverage</summary><div className="max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Player</th><th>Targets</th><th>Historical points</th><th>Workload points</th><th>Workload P10 / P90</th></tr></thead><tbody>{players.map(p=><tr className="border-t" key={p.dkPlayerId}><td className="p-2">{p.name}</td><td>{p.workload!.targets.toFixed(1)}</td><td>{p.ourProj?.toFixed(1)??'Missing'}</td><td>{p.workload!.mean.toFixed(1)}</td><td>{p.workload!.p10.toFixed(1)} / {p.workload!.p90.toFixed(1)}</td></tr>)}</tbody></table></div>{slate?.players.filter(p=>p.position==='WR'&&!p.workload).map(p=><p className="text-xs" key={p.dkPlayerId}>{p.name}: {p.workloadReason}</p>)}</details>
    <button disabled={!players.length||pending} className="rounded border bg-white px-4 py-2 disabled:opacity-40" onClick={()=>{if(!slate)return;setError('');startTransition(async()=>{try{setComparison(await compareNflWorkload(slate.uploadId,settings));}catch(e){setError(e instanceof Error?e.message:'Comparison failed.');}});}}>Generate matched comparison</button>
    <p className="text-xs">Uses your portfolio controls, up to five lineups per source, and zero randomness. Saves both runs from the same player snapshot for review after the slate.</p>
    {error&&<p role="alert">{error}</p>}
    {comparison&&<div className="space-y-2 rounded bg-white p-3"><p>{comparison.note}</p><p className="text-sm">Compared {comparison.comparedAt}. {comparison.excludedFromComparison} players excluded from the common pregame pool. These results retain the settings used when generated.</p>{(['baseline','candidate'] as const).map(source=>{const r=comparison[source];return <div key={source}>{r.result.warnings.map(w=><p key={w} className="text-xs text-amber-900">{w}</p>)}<b>{source==='baseline'?'Historical':'WR workload'}: {r.result.lineups.length} lineups saved</b><p className="text-xs">Run {r.runId}</p>{r.result.lineups.map(l=><p className="text-sm" key={l.lineupNumber}>#{l.lineupNumber}: {l.slots.map(s=>s.player.name).join(', ')} · ${l.totalSalary.toLocaleString()} · {l.projectedFpts.toFixed(1)} projected points</p>)}</div>;})}<button className="text-indigo-800 underline" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(comparison,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='nfl-workload-comparison.json';a.click();URL.revokeObjectURL(url);}}>Download comparison and frozen inputs</button></div>}
  </section>;
}
