"use client";

import type { BestBallDraftPlan, BestBallPlannedPlayer } from "@/lib/fantasy-football/best-ball-draft-plan";

export type BestBallPickReceipt = { playerName: string; position: string; overallPick: number; teamSlot: number; isUserPick: boolean; source: "manual" | "decision-desk" | "ai"; impactLabel: string; nextPick: number | null };
type Props = { plan: BestBallDraftPlan | null; canDraftRecommendation: boolean; receipt: BestBallPickReceipt | null; onDraft: (playerId: number) => void; onDismissReceipt: () => void };

function availabilityText(player: BestBallPlannedPlayer, plan: BestBallDraftPlan, canDraft: boolean) {
  const pick = canDraft ? plan.futurePick : plan.targetPick;
  const odds = canDraft ? player.availabilityAtFuture : player.availabilityAtTarget;
  if (pick === null) return "No later controlled pick";
  if (!odds) return `Pick #${pick} availability unavailable`;
  return `${Math.round(odds.probability * 100)}% available at #${pick} · ${odds.confidence} confidence · n=${odds.sampleSize ?? "unknown"}`;
}

export function BestBallDecisionDesk({ plan, canDraftRecommendation, receipt, onDraft, onDismissReceipt }: Props) {
  const label = !canDraftRecommendation ? `PLAN FOR PICK #${plan?.targetPick ?? "—"}` : plan?.primary.decision === "draft-now" ? "DRAFT NOW" : `LOW URGENCY · LIKELY AT #${plan?.futurePick}`;
  return <section className="rounded-3xl border border-blue-200 bg-blue-50 p-5 shadow-sm">
    <div><p className="text-xs font-black uppercase tracking-[0.22em] text-blue-700">Best Ball Decision Desk</p><h2 className="mt-1 text-2xl font-black">Always-on roster and availability intelligence</h2><p className="mt-1 text-sm text-blue-950/75">Deterministic board rank, legal roster construction, and directional FFC ADP survival. This does not simulate opponent picks or blend AI opinions.</p></div>
    {!plan ? <p className="mt-5 rounded-xl bg-white/70 p-4 text-sm">No legal recommendation is available.</p> : <div className="mt-5 grid gap-4 xl:grid-cols-[1.15fr_1fr]">
      <div className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-blue-700">{label}</p><h3 className="text-2xl font-black">{plan.primary.name}</h3><p className="text-sm font-semibold">{plan.primary.position} · {plan.primary.impactLabel}</p></div><button disabled={!canDraftRecommendation} onClick={() => onDraft(plan.primary.playerId)} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{canDraftRecommendation ? plan.primary.decision === "low-urgency" ? "Draft anyway" : "Draft" : "Waiting"}</button></div><p className="mt-3 text-xs text-muted-foreground">{availabilityText(plan.primary, plan, canDraftRecommendation)}</p><div className="mt-4 grid grid-cols-4 gap-2">{plan.blueprint.positions.map((row) => <div key={row.position} className="rounded-lg bg-slate-100 p-2 text-center"><p className="text-xs font-bold text-muted-foreground">{row.position}</p><p className="font-black">{row.count}<span className="text-xs font-normal text-muted-foreground"> / {row.target}</span></p><p className="text-[10px] text-muted-foreground">min {row.minimum}</p></div>)}</div><p className={`mt-3 text-xs font-semibold ${plan.blueprint.completable ? "text-emerald-700" : "text-red-700"}`}>{plan.blueprint.remainingPicks} picks left · {plan.blueprint.minimumPicksRequired} still required for minimums · {plan.blueprint.nflTeams} NFL teams</p></div>
      <div className="rounded-2xl bg-white p-4 shadow-sm"><h3 className="font-black">Board fallbacks</h3><p className="mt-1 text-xs text-muted-foreground">Highest-rated legal alternatives after construction and availability adjustments.</p><div className="mt-3 space-y-2">{plan.fallbacks.map((player, index) => <div key={player.playerId} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black text-muted-foreground">{index === 0 ? "FALLBACK" : "ALTERNATIVE"}</p><p className="font-bold">{player.name} <span className="text-xs font-normal text-muted-foreground">{player.position}</span></p><p className="text-xs text-muted-foreground">{player.impactLabel}</p><p className="text-[10px] text-muted-foreground">{availabilityText(player, plan, canDraftRecommendation)}</p></div><button disabled={!canDraftRecommendation} onClick={() => onDraft(player.playerId)} className="rounded-lg border px-3 py-1.5 text-xs font-bold disabled:opacity-40">{canDraftRecommendation ? "Draft" : "Waiting"}</button></div></div>)}</div></div>
    </div>}
    {receipt && <div className="mt-4 rounded-2xl border border-blue-300 bg-white/80 p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-black uppercase text-blue-700">Pick receipt · #{receipt.overallPick} · {receipt.source}</p><p className="font-black">{receipt.playerName} · {receipt.position}</p></div><button onClick={onDismissReceipt} className="text-xs font-bold text-blue-700">Dismiss</button></div><p className="mt-2 text-sm">{receipt.isUserPick ? receipt.impactLabel : `Team ${receipt.teamSlot} selected this player; your plan has refreshed.`} {receipt.nextPick === null ? "No controlled picks remain." : `Next controlled pick: #${receipt.nextPick}.`}</p></div>}
  </section>;
}
